[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
photon = { path = "../photon" }
websocket = "0.27.1"
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
