[package]
name = "photon"
version = "0.1.0"
edition = "2024"

[dependencies]
websocket = "0.27.1"
once_cell = "1.21.3"
dns-lookup = "2.0.4"
rand = "0.6.5"
num_enum = "0.7.3"
crossbeam-channel = "0.5.15"
