use num_enum::{TryFromPrimitive, IntoPrimitive};

#[derive(Debug, TryFromPrimitive, IntoPrimitive, Copy, Clone)]
#[repr(u8)]
pub(crate) enum GpType {
    Unknown = 0,
    Boolean = 2,
    Byte = 3,
    Short = 4,
    Float = 5,
    Double = 6,
    String = 7,
    Null = 8,
    CompressedInt = 9,
    CompressedLong = 10,
    Int1 = 11,
    Int1_ = 12,
    Int2 = 13,
    Int2_ = 14,
    L1 = 15,
    L1_ = 16,
    L2 = 17,
    L2_ = 18,
    Custom = 19,
    CustomTypeSlim = 128,
    Dictionary = 20,
    Hashtable = 21,
    ObjectArray = 23,
    OperationRequest = 24,
    OperationResponse = 25,
    EventData = 26,
    BooleanFalse = 27,
    BooleanTrue = 28,
    ShortZero = 29,
    IntZero = 30,
    LongZero = 31,
    FloatZero = 32,
    DoubleZero = 33,
    ByteZero = 34,
    Array = 64,
    BooleanArray = 66,
    ByteArray = 67,
    ShortArray = 68,
    DoubleArray = 70,
    FloatArray = 69,
    StringArray = 71,
    HashtableArray = 85,
    DictionaryArray = 84,
    CustomTypeArray = 83,
    CompressedIntArray = 73,
    CompressedLongArray = 74
}